### ISSUE TITLE
Issue: Error in pull_data function - "Could not guess the delimiter"

### ISSUE THREAD

**Issue by jahongOf1** [FlowWest/UWDtap#12]
**Description:**
I downloaded the UWDtap main branch on 8/23/2023, and followed the steps in the README guide. However, I encountered an issue when trying to use the pull_data function. Specifically, I received the "Could not guess the delimiter" error.

### Steps to Reproduce:

1. Loaded the UWDtap library:
```
library(UWDtap)
```
2. Attempted to download data for the year 2020 using the pull_data function:
```
urban_water_data <- pull_data(year_selection = 2020)
```
This produced the error.
```
Error: Could not guess the delimiter.
Use `vroom(delim =)` to specify one explicitly.
```

### Further Investigation:
Upon delving into the pull_data function, I noticed it makes use of several get_data functions:

```
...
cr <- get_cr_data() |> filter(year == year_selection)
wla <- get_wla_data() |> filter(year == year_selection)
uwmp <- get_uwmp_data() |> filter(year == year_selection)
ear <- get_ear_data(year_selection, ...)
...
```

By testing each of these functions, I found that get_wla_data generates the aforementioned delimiter error:

```
> urban_water_data <-get_wla_data()
Error: Could not guess the delimiter.
Use `vroom(delim =)` to specify one explicitly.
```

**Comment by alvizek** [comment]
Thank you for the thorough documentation. This issue is the same as issue #10 (closed) that documented adding the delimiter to the `get_wla_data()` function. The code was updated to specify `delim = "\t"` on line 58 of https://github.com/FlowWest/UWDtap/blob/main/R/pull_data.R  (`wla_data_raw <- read_delim(temp, delim = "\t")`). This issue was closed and updates merged to the main branch.

I was not able to replicate this issue following these updates.

Can you please try 1) restart your R session, 2) run the following code `remotes::install_github("flowwest/UWDtap")`? I am wondering if the version of the package you are using is not up to date.

**Comment by jahongOf1** [comment]
I apologize for the delayed response.` remotes::install_github("flowwest/UWDtap") `worked.
Thank you.
